// ═══════════════════════════════════════════════════════════
//  app.js  —  Recipe Kitchen engine
//  Do not edit this file to add recipes.
//  Edit js/recipes-index.js and recipes/*.js instead.
// ═══════════════════════════════════════════════════════════

// ── RECIPE REGISTRY ────────────────────────────────────────
// Each recipes/*.js file calls registerRecipe() to add itself.

const RECIPES = [];

function registerRecipe(recipe) {
  RECIPES.push(recipe);
}

// ── CONSTANTS ──────────────────────────────────────────────

const CATEGORY_LABELS = {
  entrees:    "Entrées",
  appetizers: "Appetizers",
  sauces:     "Sauces",
  desserts:   "Desserts",
  breakfast:  "Breakfast",
  drinks:     "Drinks",
};

const CATS = ['breakfast', 'appetizers', 'entrees', 'desserts', 'sauces', 'drinks'];

// ── LOAD RECIPE FILES ──────────────────────────────────────
// Dynamically inserts <script> tags for every file listed in
// recipes-index.js, then calls init() once they're all loaded.

function loadRecipes() {
  if (typeof RECIPE_FILES === 'undefined' || RECIPE_FILES.length === 0) {
    init();
    return;
  }

  let loaded = 0;
  const total = RECIPE_FILES.length;

  RECIPE_FILES.forEach(path => {
    const s = document.createElement('script');
    s.src = path;
    s.onload = () => { loaded++; if (loaded === total) init(); };
    s.onerror = () => {
      console.warn(`Could not load recipe file: ${path}`);
      loaded++;
      if (loaded === total) init();
    };
    document.head.appendChild(s);
  });
}

// ── RENDERING HELPERS ──────────────────────────────────────

function photoOrPlaceholder(photo, cls = "") {
  if (photo) {
    return `<div class="card-photo ${cls}"><img src="${photo}" alt="Recipe photo" loading="lazy"></div>`;
  }
  return `<div class="card-photo placeholder ${cls}">
    <svg width="40" height="40" viewBox="0 0 40 40" fill="none">
      <rect x="4" y="8" width="32" height="24" rx="2" stroke="#9A7560" stroke-width="1.5"/>
      <circle cx="14" cy="17" r="3" stroke="#9A7560" stroke-width="1.5"/>
      <path d="M4 27l8-6 6 5 5-4 9 8" stroke="#9A7560" stroke-width="1.5" stroke-linecap="round"/>
    </svg>
    <span>No photo yet</span>
  </div>`;
}

function renderCard(recipe) {
  const label = CATEGORY_LABELS[recipe.category] || recipe.category;
  return `
    <a class="recipe-card" href="#" onclick="openRecipe('${recipe.id}'); return false;">
      ${photoOrPlaceholder(recipe.photo)}
      <div class="card-body">
        <div class="card-tag">${label}</div>
        <div class="card-title">${recipe.title}</div>
        <div class="card-desc">${recipe.description}</div>
        <div class="card-meta">
          <span>⏱ ${recipe.prepTime} prep</span>
          <span>🔥 ${recipe.cookTime}</span>
          <span>🍽 ${recipe.servings}</span>
        </div>
      </div>
    </a>`;
}

// ── COMPONENT NORMALISER ───────────────────────────────────
// Converts both recipe formats into a unified components array:
//
//   SIMPLE (legacy):
//     { ingredients: [...], steps: [...] }
//
//   MULTI-COMPONENT:
//     { components: [{ name, ingredients, steps }, ...] }
//
// After normalisation, every recipe has `recipe.components`.

function normaliseComponents(recipe) {
  if (recipe.components) return recipe.components;
  return [{
    name:        null,
    ingredients: recipe.ingredients || [],
    steps:       recipe.steps       || [],
  }];
}

// ── RENDER HELPERS ─────────────────────────────────────────

function renderIngredientList(ingredients) {
  return ingredients.map(i =>
    `<li><span>${i.name}</span><span class="amount">${i.amount}</span></li>`
  ).join('');
}

function renderSteps(steps, startAt = 1) {
  return steps.map((s, idx) =>
    `<div class="step">
      <div class="step-number">${startAt + idx}</div>
      <div class="step-text">${s}</div>
    </div>`
  ).join('');
}

function renderRecipePage(recipe) {
  const label      = CATEGORY_LABELS[recipe.category] || recipe.category;
  const components = normaliseComponents(recipe);
  const isMulti    = components.length > 1 || components[0].name;

  const photoHtml = recipe.photo
    ? `<div class="recipe-photo-wrap"><img src="${recipe.photo}" alt="${recipe.title}"></div>`
    : `<div class="recipe-photo-wrap placeholder">
         <svg width="60" height="60" viewBox="0 0 40 40" fill="none">
           <rect x="4" y="8" width="32" height="24" rx="2" stroke="#9A7560" stroke-width="1.5"/>
           <circle cx="14" cy="17" r="3" stroke="#9A7560" stroke-width="1.5"/>
           <path d="M4 27l8-6 6 5 5-4 9 8" stroke="#9A7560" stroke-width="1.5" stroke-linecap="round"/>
         </svg>
         <span>Set photo: in your recipe file</span>
       </div>`;

  // ── Ingredients sidebar ──────────────────────────────────
  let ingredientsSidebarHtml;
  if (isMulti) {
    ingredientsSidebarHtml = components.map(c => `
      ${c.name ? `<div class="component-heading">${c.name}</div>` : ''}
      <ul class="ingredient-list">${renderIngredientList(c.ingredients)}</ul>
    `).join('');
  } else {
    ingredientsSidebarHtml = `<ul class="ingredient-list">${renderIngredientList(components[0].ingredients)}</ul>`;
  }

  // ── Instructions panel ───────────────────────────────────
  let instructionsHtml;
  if (isMulti) {
    let stepCounter = 1;
    instructionsHtml = components.map(c => {
      const block = `
        ${c.name ? `<div class="component-section-heading">${c.name}</div>` : ''}
        ${renderSteps(c.steps, stepCounter)}`;
      stepCounter += c.steps.length;
      return block;
    }).join('');
  } else {
    instructionsHtml = renderSteps(components[0].steps);
  }

  const notesHtml = recipe.notes
    ? `<div class="recipe-notes"><h4>Chef's Notes</h4><p>${recipe.notes}</p></div>`
    : '';

  return `
    <div class="recipe-hero">
      ${photoHtml}
      <div class="recipe-intro">
        <div class="recipe-category-tag">${label}</div>
        <h1 class="recipe-title">${recipe.title}</h1>
        <p class="recipe-description">${recipe.description}</p>
        <div class="recipe-stats">
          <div class="stat"><div class="stat-label">Prep</div><div class="stat-value">${recipe.prepTime}</div></div>
          <div class="stat"><div class="stat-label">Cook</div><div class="stat-value">${recipe.cookTime}</div></div>
          <div class="stat"><div class="stat-label">Serves</div><div class="stat-value">${recipe.servings}</div></div>
        </div>
      </div>
    </div>
    <div class="recipe-body">
      <aside class="ingredients-panel">
        <div class="panel-title">Ingredients</div>
        ${ingredientsSidebarHtml}
      </aside>
      <div class="instructions-panel">
        <h3>Instructions</h3>
        ${instructionsHtml}
        ${notesHtml}
      </div>
    </div>`;
}

// ── NAVIGATION ─────────────────────────────────────────────

let currentCategory = null;
let currentRecipe   = null;
let currentSearch   = '';

function hideAll() {
  document.getElementById('home-section').style.display = 'none';
  document.getElementById('hero-banner').style.display  = 'none';
  document.getElementById('recipe-page').classList.remove('active');
  document.getElementById('search-section').classList.remove('active');
  document.querySelectorAll('.category-section').forEach(s => s.classList.remove('active'));
  document.querySelectorAll('nav a').forEach(a => a.classList.remove('active'));
}

function showHome() {
  hideAll();
  document.getElementById('home-section').style.display = 'block';
  document.getElementById('hero-banner').style.display  = 'block';
  document.getElementById('nav-home').classList.add('active');
  currentCategory = null; currentRecipe = null; currentSearch = '';
  document.getElementById('search-input').value = '';
  document.getElementById('search-clear').style.display = 'none';
  document.getElementById('search-icon').style.display  = 'block';
}

function showCategory(cat) {
  hideAll();
  document.getElementById(`section-${cat}`).classList.add('active');
  document.getElementById(`nav-${cat}`).classList.add('active');
  currentCategory = cat; currentRecipe = null; currentSearch = '';
  document.getElementById('search-input').value = '';
  document.getElementById('search-clear').style.display = 'none';
  document.getElementById('search-icon').style.display  = 'block';
  window.scrollTo({ top: 0, behavior: 'smooth' });
}

function openRecipe(id) {
  const recipe = RECIPES.find(r => r.id === id);
  if (!recipe) return;
  hideAll();
  document.getElementById('recipe-detail-content').innerHTML = renderRecipePage(recipe);
  document.getElementById('recipe-page').classList.add('active');
  currentRecipe = id;
  window.scrollTo({ top: 0, behavior: 'smooth' });
}

function closeRecipe() {
  if (currentSearch) {
    document.getElementById('search-input').value = currentSearch;
    showSearchResults(currentSearch);
  } else if (currentCategory) {
    showCategory(currentCategory);
  } else {
    showHome();
  }
}

// ── SEARCH ─────────────────────────────────────────────────

let searchQuery = '';

function handleSearch(val) {
  searchQuery = val.trim();
  const clearBtn   = document.getElementById('search-clear');
  const searchIcon = document.getElementById('search-icon');

  if (!searchQuery) {
    clearBtn.style.display   = 'none';
    searchIcon.style.display = 'block';
    showHome();
    return;
  }

  clearBtn.style.display   = 'block';
  searchIcon.style.display = 'none';
  showSearchResults(searchQuery);
}

function clearSearch() {
  document.getElementById('search-input').value = '';
  document.getElementById('search-clear').style.display = 'none';
  document.getElementById('search-icon').style.display  = 'block';
  searchQuery = '';
  showHome();
}

function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function highlightText(text, query) {
  if (!query) return text;
  const re = new RegExp(`(${escapeRegex(query)})`, 'gi');
  return text.replace(re, '<mark>$1</mark>');
}

function scoreRecipe(recipe, query) {
  const q          = query.toLowerCase();
  const components = normaliseComponents(recipe);
  let score        = 0;

  if (recipe.title.toLowerCase().includes(q))       score += 10;
  if (recipe.description.toLowerCase().includes(q)) score += 5;
  if (recipe.category.toLowerCase().includes(q))    score += 4;

  for (const c of components) {
    if (c.name && c.name.toLowerCase().includes(q)) score += 3;
    if (c.ingredients.some(i =>
      i.name.toLowerCase().includes(q) || i.amount.toLowerCase().includes(q)
    )) score += 3;
    if (c.steps.some(s => s.toLowerCase().includes(q))) score += 1;
  }

  return score;
}

function renderCardHighlighted(recipe, query) {
  const label = CATEGORY_LABELS[recipe.category] || recipe.category;
  return `
    <a class="recipe-card" href="#" onclick="openRecipeFromSearch('${recipe.id}'); return false;">
      ${photoOrPlaceholder(recipe.photo)}
      <div class="card-body">
        <div class="card-tag">${label}</div>
        <div class="card-title">${highlightText(recipe.title, query)}</div>
        <div class="card-desc">${highlightText(recipe.description, query)}</div>
        <div class="card-meta">
          <span>⏱ ${recipe.prepTime} prep</span>
          <span>🔥 ${recipe.cookTime}</span>
          <span>🍽 ${recipe.servings}</span>
        </div>
      </div>
    </a>`;
}

function showSearchResults(query) {
  hideAll();
  document.getElementById('search-section').classList.add('active');

  const scored = RECIPES
    .map(r  => ({ recipe: r, score: scoreRecipe(r, query) }))
    .filter(x => x.score > 0)
    .sort((a, b)  => b.score - a.score);

  document.getElementById('search-query-display').textContent = `"${query}"`;
  document.getElementById('search-count').textContent =
    `${scored.length} result${scored.length !== 1 ? 's' : ''}`;

  const grid = document.getElementById('search-grid');

  if (!scored.length) {
    grid.innerHTML = `
      <div class="no-results" style="grid-column:1/-1">
        <svg width="56" height="56" viewBox="0 0 40 40" fill="none">
          <circle cx="17" cy="17" r="11" stroke="#6B3A20" stroke-width="1.5"/>
          <path d="M26 26l8 8" stroke="#6B3A20" stroke-width="1.5" stroke-linecap="round"/>
          <path d="M13 17h8M17 13v8" stroke="#C57B57" stroke-width="1.5" stroke-linecap="round"/>
        </svg>
        <h3>No recipes found</h3>
        <p>Try a different ingredient, dish name, or category.</p>
      </div>`;
    return;
  }

  grid.innerHTML = scored.map(x => renderCardHighlighted(x.recipe, query)).join('');
}

function openRecipeFromSearch(id) {
  const prev = searchQuery;
  openRecipe(id);
  currentSearch = prev;
}

// ── INIT ───────────────────────────────────────────────────

function init() {
  // Fill category grids
  CATS.forEach(cat => {
    const items = RECIPES.filter(r => r.category === cat);
    document.getElementById(`grid-${cat}`).innerHTML =
      items.map(renderCard).join('') ||
      `<p style="color:var(--muted);font-family:'Lora',serif;font-size:.9rem">No recipes yet in this category.</p>`;
    document.getElementById(`count-${cat}`).textContent =
      `${items.length} recipe${items.length !== 1 ? 's' : ''}`;
  });

  // Build home page (3 per category max, skip empty)
  const container = document.getElementById('all-categories-container');
  container.innerHTML = CATS.map(cat => {
    const items = RECIPES.filter(r => r.category === cat);
    if (!items.length) return '';
    const label = CATEGORY_LABELS[cat];
    return `
      <div class="cat-block">
        <div class="section-header">
          <h2>${label}</h2>
          <span class="count">${items.length} recipe${items.length !== 1 ? 's' : ''}</span>
          <button class="see-all" onclick="showCategory('${cat}')">See all →</button>
        </div>
        <div class="recipe-grid">${items.slice(0, 3).map(renderCard).join('')}</div>
      </div>`;
  }).join('');
}