registerRecipe({
  id:          "aloo-methi",
  category:    "entrees",
  title:       "Aloo Methi",
  description: "A simple, homestyle dry curry of potatoes and fresh fenugreek leaves, tempered with cumin and whole spices. Earthy, slightly bitter, and deeply comforting.",
  photo:       "photos/aloo-methi.png",           // e.g. "photos/aloo-methi.jpg"
  prepTime:    "15 min",
  cookTime:    "30 min",
  servings:    "4",
  ingredients: [
    { amount: "5 medium",  name: "potatoes, peeled and cut into 1\" cubes" },
    { amount: "2 cups",    name: "fresh methi (fenugreek) leaves, washed and roughly chopped" },
    { amount: "2 tbsp",    name: "oil or ghee" },
    { amount: "2 tsp",     name: "cumin seeds" },
    { amount: "1 pinch",   name: "hing (asafoetida)" },
    { amount: "4 cloves",  name: "garlic, finely chopped" },
    { amount: "1 inch",    name: "ginger, finely chopped" },
    { amount: "1",         name: "green chillies, chopped" },
    { amount: "1 medium",  name: "onion, finely chopped" },
    { amount: "1",         name: "tomato, finely chopped" },
	{ amount: "½ tsp",     name: "turmeric powder" },
    { amount: "1 tsp",     name: "coriander powder" },
    { amount: "½ tsp",     name: "red chilli powder" },
    { amount: "2½ tsp",    name: "sugar (to cut the bitterness)" },
    { amount: "to taste",  name: "salt" },
    { amount: "½ tsp",     name: "garam masala" },
  ],
  steps: [
    "Wash the methi leaves well and sprinkle with a pinch of salt. Set aside for 10 minutes, then squeeze out any excess moisture — this reduces bitterness.",
    "Heat oil or ghee in a wide kadhai over medium-high heat. Add the cumin seeds and hing. Let the seeds splutter.",
    "Add the garlic, ginger, and green chillies. Sauté for 1 minute until fragrant.",
    "Add the onion and cook until golden, about 6–8 minutes.",
    "Add the turmeric, coriander powder, and red chilli powder. Mix well and cook for 1 minute.",
    "Add the potato cubes and stir to coat in the spices. Cook on medium heat for 8–10 minutes, stirring occasionally, until the potatoes are about halfway cooked. Cook with lid on for faster cooking.",
    "Add splashes of water when needed to prevent potatoes from sticking.",
    "Add the chopped tomatoes and cook for about 3-4 minutes.",
	"Add the methi leaves, and sugar. Mix well. The leaves will wilt down quickly.",
    "Reduce heat to low, cover, and cook for another 8–10 minutes until the potatoes are fully cooked through. Stir once or twice to prevent sticking.",
    "Uncover and cook on high for 1–2 minutes to dry out any remaining moisture. Add garam masala, toss well, and serve.",
  ],
  notes: "The salting and squeezing step for the methi is worth doing — fresh fenugreek leaves can be quite bitter straight from the bunch. If fresh methi is unavailable, use 3 tbsp of dried kasuri methi instead, added directly with the spices.",
});