registerRecipe({
  id:          "barramundi-masala",
  category:    "entrees",
  title:       "Barramundi Masala",
  description: "Tender barramundi fillets simmered in a boldly spiced tomato-onion masala with whole cumin and mustard seeds. Rich, warming, and ready in under 30 minutes.",
  photo:       "photos/barramundi-masala.png",           // e.g. "photos/barramundi-masala.jpg"
  prepTime:    "10 min",
  cookTime:    "25 min",
  servings:    "4",
  ingredients: [
    { amount: "4 fillets",  name: "barramundi (or other firm white fish)" },
    { amount: "2 tbsp",     name: "oil" },
    { amount: "1 tsp",      name: "mustard seeds" },
    { amount: "1 tsp",      name: "cumin seeds" },
    { amount: "1 pinch",    name: "hing (asafoetida)" },
    { amount: "½",          name: "onion, grated" },
    { amount: "2 cloves",   name: "garlic, minced" },
    { amount: "1 tsp",      name: "ginger paste" },
    { amount: "2 tbsp",     name: "tomato paste, mixed with ¼ cup warm water" },
    { amount: "¼ tsp",     name: "clove powder" },
    { amount: "3 tsp",      name: "coriander powder" },
    { amount: "1 tsp",      name: "red chilli powder" },
    { amount: "2 tsp",      name: "meat masala" },
    { amount: "1 tsp",      name: "turmeric" },
    { amount: "1 tsp",      name: "garam masala" },
    { amount: "1 pinch",    name: "kasuri methi (dried fenugreek leaves)" },
    { amount: "as needed",  name: "water" },
  ],
  steps: [
    "Heat oil in a wide pan over medium-high heat. Add the mustard seeds, cumin seeds, and hing. Cook until the seeds begin to splutter.",
    "Add the grated onion paste along with the garlic and ginger paste. Sauté until the oil separates from the mixture — about 8–10 minutes.",
    "Add the tomato paste mixed with warm water. Stir well and cook until the mixture thickens and the oil separates again.",
    "Add the clove powder, coriander powder, red chilli powder, meat masala, and turmeric. Mix well and cook for 2 minutes.",
    "Add the fish pieces and enough water to just surround them. Cook on medium heat for 10 minutes.",
    "Add the kasuri methi and garam masala. Stir gently, reduce heat to low, and cook for a further 5 minutes until the fish is cooked through.",
  ],
  notes: "Barramundi is delicate — avoid stirring too vigorously once the fish is in or it will break apart. A wide, shallow pan helps the pieces cook evenly without crowding.",
});
