registerRecipe({
  id:          "chicken-masala",
  category:    "entrees",
  title:       "Chicken Masala",
  description: "Bone-in chicken leg quarters cooked in a pressure cooker with a deeply aromatic ground masala paste of roasted spices, tomato, and onion. Bold, rich, and full of depth.",
  photo:       "photos/chicken-masala.png",           // e.g. "photos/chicken-masala.jpg"
  prepTime:    "20 min",
  cookTime:    "30 min",
  servings:    "2",
  ingredients: [
    { amount: "1 kg",      name: "chicken leg quarters" },
    { amount: "1 tbsp",    name: "ghee" },
    { amount: "1 tsp",     name: "oil" },
    { amount: "1 medium",  name: "onion, roughly cut" },
    { amount: "2",         name: "Roma tomatoes, roughly cut" },
    { amount: "1 tbsp",    name: "tomato paste" },
    { amount: "3 cloves",  name: "garlic" },
    { amount: "1 inch",    name: "ginger" },
    { amount: "1",         name: "green chilli" },
    { amount: "1 tsp",     name: "cumin seeds" },
    { amount: "1 tsp",     name: "coriander seeds" },
    { amount: "4",         name: "green cardamoms" },
    { amount: "1 pinch",   name: "asafoetida (hing)" },
    { amount: "2 heaping tsp", name: "Everest chicken masala" },
    { amount: "1 tsp",     name: "coriander powder" },
    { amount: "2 tsp",     name: "garam masala, divided" },
    { amount: "1 pinch",   name: "red chilli powder" },
    { amount: "1 tbsp",    name: "dried fenugreek leaves (kasuri methi), crushed" },
    { amount: "4 tbsp",    name: "fresh coriander leaves, chopped" },
    { amount: "to taste",  name: "salt" },
    { amount: "as needed", name: "water" },
  ],
  steps: [
    "Heat ghee in a pressure cooker over medium heat. Add the cumin seeds, coriander seeds, hing, and cardamom. Roast for 2 minutes until fragrant.",
    "Add the garlic, green chilli, and ginger. Cook for a few minutes.",
    "Add the onion and cook until translucent.",
    "Add the tomatoes and a pinch of salt. Cook until the tomatoes are completely mushy.",
    "Remove the entire mixture from the cooker and grind to a smooth paste.",
    "Heat the oil in the same pressure cooker. Add the ground paste back in.",
    "Add the tomato paste, chicken masala, salt, coriander powder, 1 tsp garam masala, and red chilli powder. Mix well and cook for about 5 minutes, until the oil begins to separate.",
    "Add the chicken leg quarters and mix well to coat in the masala.",
    "Add just enough water to cover the chicken halfway. Close the lid and pressure cook until 1 whistle.",
    "Open the cooker and stir in the crushed kasuri methi, remaining 1 tsp garam masala, and fresh coriander leaves. Serve hot.",
  ],
  notes: "The key step is cooking the paste long enough in step 7 until the oil separates — this ensures the raw spice taste is gone before the chicken goes in.",
});
