registerRecipe({
  id:          "cowboy-cookies",
  category:    "desserts",
  title:       "Cowboy Cookies",
  description: "Hearty, chewy cookies packed with oats, toasted pecans, shredded coconut, and chocolate chips. Big, satisfying, and impossible to eat just one.",
  photo:       "photos/cowboy-cookies.png",           // e.g. "photos/cowboy-cookies.jpg"
  prepTime:    "15 min",
  cookTime:    "17 min",
  servings:    "24 cookies",
  ingredients: [
    { amount: "1.25 cups", name: "all-purpose flour, sifted" },
    { amount: "¾ tsp",    name: "baking powder" },
    { amount: "½ tsp",    name: "baking soda" },
    { amount: "½ tsp",    name: "salt" },
    { amount: "1.5 cups",  name: "sugar" },
    { amount: "12 tbsp",   name: "unsalted butter, melted" },
    { amount: "1 large",   name: "egg (whole)" },
    { amount: "1 large",   name: "egg yolk (yolk only)" },
    { amount: "1 tsp",     name: "vanilla extract" },
    { amount: "1.25 cups", name: "old-fashioned rolled oats or quick oats" },
    { amount: "1 cup",     name: "pecans, toasted (or walnuts)" },
    { amount: "1 cup",     name: "shredded coconut, sweetened" },
    { amount: "⅔ cup",    name: "chocolate chips" },
  ],
  steps: [
    "Preheat oven to 350°F. Line baking sheets with parchment paper.",
    "In a large bowl, whisk together the melted butter, sugar, whole egg, egg yolk, and vanilla extract until combined.",
    "Add the flour, baking powder, baking soda, and salt. Stir until just combined.",
    "Fold in the oats, pecans, coconut, and chocolate chips until evenly incorporated.",
    "Scoop dough onto the prepared baking sheets, spacing well apart. Bake for 15–17 minutes, rotating the sheet halfway through.",
    "Remove when the edges are just set but the centers still look slightly soft. Leave on the baking tray for 5 more minutes before transferring to a cooling rack.",
  ],
  notes: "The extra yolk (no white) is intentional — it makes the cookies richer and chewier. Pull them from the oven when they look underdone; they firm up as they cool.",
});
