registerRecipe({
  id:          "gajar-mattar",
  category:    "entrees",
  title:       "Gajar Mattar",
  description: "Tender sweet carrots and bright green peas cooked in a lightly spiced, buttery tomato-onion masala. A simple, wholesome sabzi that comes together quickly and pairs beautifully with roti or paratha.",
  photo:       "photos/gajar-mattar.png",           // e.g. "photos/aloo-methi.jpg"
  prepTime:    "15 min",
  cookTime:    "30 min",
  servings:    "4",
  ingredients: [
    { amount: "4 medium",  name: "red carrots, peeled and cut into discs (can substitute with orange carrots)" },
    { amount: "1 cup",     name: "sweet peas" },
    { amount: "2 tbsp",    name: "mustard oil or ghee (can substitute with avocado oil)" },
    { amount: "2 tsp",     name: "cumin seeds" },
    { amount: "1 medium",  name: "onion, finely chopped" },
	{ amount: "½ tsp",     name: "turmeric powder" },
    { amount: "½ tsp",     name: "red chilli powder" },
    { amount: "to taste",  name: "salt" },
	{ amount: "a pinch",   name: "kasuri methi" },
	{ amount: "1 bunch",   name: "fresh cilantro, chopped" },
  ],
  steps: [
    "Wash and peel the carrots. Cut them into discs of equal size for even cooking. Discs at the broader end can be cut into half.",
    "If using mustard oil, heat the oil till it starts smoking. Turn the heat off and let the oil cool a bit before adding the cumin seeds. This will reduce the pungency and prevent the cumin seeds from burning.",
    "Add the onion and cook for about 3-4 minutes. The goal is to slightly cook the onions, not brown them.",
	"Add the carrots and peas and stir.",
    "Add the salt and turmeric. Mix well and cook for 10 minutes with a lid on. Cook on medium to low heat.",
    "Only add splashes of water if really needed. Adding water can change the flavor.",
    "Check if the carrots are done by cutting into a large piece. If done, then add red chilli powder. Add the chilli powder only at the end to preserve the color.",
    "Garnish with freshly chopped cilantro and kasuri methi. Give it another mix and serve with roti or paratha.",
  ],
  notes: "Use the sweetest carrots you can find. The natural sweetness is what makes this dish sing, so it's worth seeking out fresh seasonal carrots over bagged ones.",
});