registerRecipe({
  id:          "masala-chai",
  category:    "drinks",
  title:       "Masala Chai",
  description: "A warming, spiced milk tea brewed with whole cardamom, ginger, and cinnamon. Bold, fragrant, and deeply comforting, the kind that fills the whole kitchen with aroma.",
  photo:       "photos/masala-chai.png",           // e.g. "photos/masala-chai.jpg"
  prepTime:    "5 min",
  cookTime:    "15 min",
  servings:    "2",
  ingredients: [
    { amount: "1.5 cup",  name: "water" },
    { amount: "0.5 cup",  name: "whole milk (can adjust to taste)" },
    { amount: "2 tsp",    name: "loose leaf black tea" },
    { amount: "2 tsp",    name: "sugar, or to taste" },
    { amount: "1 inch",   name: "ginger, roughly crushed or grated" },
    { amount: "6",        name: "green cardamoms, lightly crushed" },
    { amount: "1 inch",   name: "cinnamon stick" },
    { amount: "4",        name: "cloves" },
    { amount: "1",        name: "star anise (optional)" },
    { amount: "1 tsp",    name: "fennel seeds (optional, great for summer because they are cooling)" },
  ],
  steps: [
    "Add the water, ginger, cardamom, cinnamon, cloves, star anise, and fennel to a small saucepan. Bring to a boil over medium-high heat.",
    "Once boiling, reduce heat and simmer for 1-2 minutes to let the spices bloom and infuse the water.",
    "Add the tea leaves and sugar. Stir and simmer for 3-4 minutes.",
    "Pour in the milk and increase heat to medium-high. Bring to a gentle boil. Watch the milk carefully; milk boils over quickly.",
    "Once it rises twice, turn the heat off, and it let rest for 5 minutes with the lid on.",
    "Strain through a fine mesh strainer into cups. Serve immediately.",
  ],
  notes: "The key is letting the spices simmer in just water first before the milk goes in. This extracts far more flavor than adding everything at once. Strong, malty tea works best here; Assam or a Irish breakfast holds up well against the spices. For a thicker, creamier chai, swap some of the water for extra milk. Adjust sugar before adding the milk so you can taste as you go. You can which spices you add based on your taste.",
});
