registerRecipe({
  id:          "poha",
  category:    "breakfast",
  title:       "Poha",
  description: "Fluffy flattened rice tempered with mustard seeds, curry leaves, and turmeric, tossed with onion, potato, and peanuts. A quick, light, and deeply satisfying Indian breakfast.",
  photo:       "photos/poha.png",           // e.g. "photos/poha.jpg"
  prepTime:    "10 min",
  cookTime:    "15 min",
  servings:    "2",
  ingredients: [
    { amount: "1.5 cups",  name: "poha (thick flattened rice)" },
    { amount: "2 tbsp",    name: "avocado or peanut oil" },
    { amount: "1 tsp",     name: "mustard seeds" },
    { amount: "1 pinch",   name: "hing (asafoetida)" },
    { amount: "10 leaves", name: "curry leaves" },
    { amount: "2",         name: "green chillies, slit" },
    { amount: "1 medium",  name: "onion, finely diced" },
    { amount: "2 medium",  name: "potato, cut into small cubes" },
	{ amount: "1 medium",  name: "carrot, cut into small cubes" },
	{ amount: "½ cup",     name: "peas" },
	{ amount: "½ cup",     name: "corn (optional)" },
    { amount: "¼ cup",     name: "peanuts" },
    { amount: "½ tsp",     name: "turmeric powder" },
    { amount: "½ tsp",     name: "red chilli powder" },
    { amount: "to taste",  name: "salt" },
    { amount: "2 tsp",     name: "lemon juice" },
    { amount: "2 tbsp",    name: "fresh cilantro, chopped" },
    { amount: "2 tbsp",    name: "fresh grated coconut (optional)" },
    { amount: "to serve",  name: "sev (optional, for topping)" },
  ],
  steps: [
    "Place the poha in a fine mesh strainer and rinse gently under cold water for 20–30 seconds, tossing lightly with your fingers. The poha should be moist and just tender but not mushy. Set aside to drain for 5 minutes.",
    "Sprinkle the turmeric, red chilli powder, and salt over the drained poha and toss gently to coat evenly. Set aside.",
    "Heat oil in a wide pan or kadhai over medium-high heat. Add the potato cubes and cook over medium heat, stirring occasionally, until cooked through and lightly golden — about 6–8 minutes.",
	"Add the peanuts and fry, stirring, until golden — about 2 minutes. Remove both and set aside.",
    "In the same pan, add the mustard seeds and hing. When the seeds splutter, add the curry leaves and green chillies. Cook for 30 seconds.",
    "Add the onion and sauté until softened and translucent, about 3 minutes.",
	"Add all remaining vegetables and saute until carrots are soft.",
    "Reduce heat to low. Add the seasoned poha to the pan. Toss gently to combine everything — avoid over-stirring or the poha will break.",
    "Cover and cook on low for 2 minutes to allow the flavors to meld.",
	"Add the potatoes and peanuts, mixing it gently with the poha.", 
    "Remove from heat. Add the lemon juice and fresh cilantro and toss lightly. Taste and adjust salt or lemon as needed.",
    "Serve immediately, topped with grated coconut and sev if using.",
  ],
  notes: "Use thick poha — thin poha turns soggy very quickly. The rinse should be brief; you want it moist, not waterlogged. Squeeze a grain between your fingers — it should flatten easily without crumbling.",
});
