registerRecipe({
  id:          "upma",
  category:    "breakfast",
  title:       "Upma",
  description: "A savory semolina porridge tempered with mustard seeds, curry leaves, and dal, loaded with vegetables. A wholesome South Indian breakfast staple.",
  photo:       "photos/upma.png",           // e.g. "photos/upma.jpg"
  prepTime:    "10 min",
  cookTime:    "20 min",
  servings:    "4",
  ingredients: [
    { amount: "1.5 tbsp",  name: "avocado oil" },
    { amount: "1 small",   name: "onion, diced" },
    { amount: "1 inch",    name: "ginger, diced" },
    { amount: "1 tsp",     name: "mustard seeds" },
    { amount: "1 pinch",   name: "hing (asafoetida)" },
    { amount: "2 tsp",     name: "chana dal" },
    { amount: "1 tsp",     name: "urad dal (dhuli huyi)" },
    { amount: "10",        name: "cashews, halved" },
    { amount: "10 leaves", name: "curry leaves" },
    { amount: "1 cup",     name: "sooji (semolina), roasted" },
    { amount: "1.5 cups",  name: "water, hot" },
    { amount: "¾ cup",     name: "mixed vegetables (corn, peas, beans, carrots)" },
    { amount: "1 tsp",     name: "red chilli powder" },
    { amount: "to taste",  name: "salt" },
  ],
  steps: [
    "Roast the sooji on low to medium heat till it turns slightly brown and aromatic.",
	"Dice the onions, ginger, and vegetables. If using frozen vegetables, soak them in hot water for 10 minutes then drain before cooking.",
    "Heat the oil in a kadhai over high heat. Add the mustard seeds and hing. When the seeds start spluttering, add the chana dal, urad dal, curry leaves, cashews, and ginger. Cook for 45 seconds on high flame.",
    "Reduce to medium heat and add the onions. Cook until translucent.",
    "Add the salt and red chilli powder and mix well.",
    "Add the vegetables and cook until soft.",
    "Make sure the hot water is ready before the next step. Add the sooji and mix thoroughly.",
    "Add 1 cup of the hot water, stirring continuously to prevent lumps.",
    "Add the remaining water and stir. Adjust consistency by adding more water to taste.",
    "Cover the kadhai and let steam for 5 minutes. Serve hot with coconut chutney.",
  ],
  notes: "Have the hot water ready before adding the sooji — it needs to go in immediately. Roasting the sooji beforehand prevents it from clumping and adds a nuttier flavor.",
});
